# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GitHubRepo\LaGauffreEmpoisonne\.metadata\.plugins\org.eclipse.jdt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


